name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Keepalive Action
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: false # 关键：关闭 API，改为直接提交代码
