name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Manual Keepalive
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          date > keepalive.txt
          git add keepalive.txt
          git commit -m "Keepalive: $(date)" || exit 0
          git push
